version: "3.3"
services:
  app:
    build:
      context: ./
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
    ports:
      - "8080:8080"
    networks:
      - internal
    depends_on:
      - postgres

  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - internal

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus:/prometheus
    ports:
      - "9090:9090"
    networks:
      - internal
    depends_on:
      - app

  grafana:
    image: grafana/grafana:$GRAFANA_VERSION
    environment:
      GF_SECURITY_ADMIN_USER: $GRAFANA_ADMIN_USER
      GF_SECURITY_ADMIN_PASSWORD: $GRAFANA_ADMIN_PASSWORD
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
      - loki
    networks:
      - internal

  loki:
    image: grafana/loki:$LOKI_VERSION
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - internal

  promtail:
    image: grafana/promtail:$PROMTAIL_VERSION
    volumes:
      - ./promtail/promtail-local-config.yml:/etc/promtail/promtail-local-config.yml
      - ./log:/var/log
    command: -config.file=/etc/promtail/promtail-local-config.yml
    networks:
      - internal

volumes:
  postgres:
  prometheus:
  grafana-storage:

networks:
  internal: