global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'app:8080' ]
        labels:
          job: 'app'
          env: staging
    # only on dev environment!
    basic_auth:
      username: spring
      password: spring