version: '3.3'
services:
  ### CODE ANALYSIS ###
  sonarqube:
    image: sonarqube:$SONAR_VERSION
    ports:
      - "9000:9000"
    networks:
      - internal
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      - sonarqube_config
    stop_grace_period: 5m

  sonarqube_config:
    image: alpine:$SONAR_CONFIG_VERSION
    environment:
      SONAR_URL: $SONAR_URL
      SONAR_USER: $SONAR_USER
      SONAR_PASSWORD: $SONAR_PASSWORD
    entrypoint: ["sh", "/docker-entrypoint.sh"]
    volumes:
      - ./sonarqube/import_data.sh:/docker-entrypoint.sh:ro
      - ./sonarqube/java_profile.xml:/java_profile.xml:ro
    networks:
      - internal
  ### END CODE ANALYSIS ###

networks:
  internal:

volumes:
  sonarqube_data:
  sonarqube_extensions: